export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const GET_VIDEO = 'GET_VIDEO';
export const UPDATE_SIDE_PANEL = 'UPDATE_SIDE_PANEL';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';
export const SET_DELAY = 'SET_DELAY';